{
  parserClass="in.ssushant.sdk.language.parser.CanadianPostalCodeParser"
  parserUtilClass="in.ssushant.sdk.language.parser.CanadianPostalCodeParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="CanadianPostalCode"
  psiImplClassSuffix="Impl"
  psiPackage="in.ssushant.sdk.language.psi"
  psiImplPackage="in.ssushant.sdk.language.psi.impl"

  elementTypeHolderClass="in.ssushant.sdk.language.psi.CanadianPostalCodeTypes"
  elementTypeClass="in.ssushant.sdk.language.psi.CanadianPostalCodeElementType"
  tokenTypeClass="in.ssushant.sdk.language.psi.CanadianPostalCodeTokenType"

  psiImplUtilClass="in.ssushant.sdk.language.psi.impl.CanadianPostalCodePsiImplUtil"

  tokens = [
     rural = 'regexp:[0]'
     urban = 'regexp:[1-9]'
     space = 'regexp:\s'
     provarea='regexp:[ABCEGHJKLMNPRSTVWXY]'
     localdeliveryunit = 'regexp:\d[ABCEGHJKLMNPRSTVWXYZ]\d'
     letter = 'regexp:[ABCEGHJKLMNPRSTVWXYZ]'
  ]
}
canadianPostalCodeFile ::= item_*

item_ ::= (postalCode|COMMENT|CRLF)

postalCode           ::= forwardsortationarea space localdeliveryunit
forwardsortationarea ::= provarea loctype provarea
loctype              ::= urban | rural