{
  parserClass="org.intellij.sdk.language.parser.CanadianPostalCodeParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="CanadianPostalCode"
  psiImplClassSuffix="Impl"
  psiPackage="in.ssushant.sdk.language.psi"
  psiImplPackage="in.ssushant.sdk.language.psi.impl"

  elementTypeHolderClass="in.ssushant.sdk.language.psi.SCanadianPostalCodeTypes"
  elementTypeClass="org.intellij.sdk.language.psi.CanadianPostalCodeElementType"
  tokenTypeClass="org.intellij.sdk.language.psi.CanadianPostalCodeTokenType"

  psiImplUtilClass="in.ssushant.sdk.language.psi.impl.CanadianPostalCodePsiImplUtil"
}

<postalcode>           ::= <forwardsortationarea> <space> <localdeliveryunit>
  <forwardsortationarea> ::= <provarea> <loctype> <letter>
  <localdeliveryunit>    ::= <digit> <letter> <digit>
  <provarea>             ::= A | B | C | E | G | H | J | K | L | M | N |
                             P | R | S | T | V | X | Y
  <loctype>              ::= <rural> | <urban>
  <rural>                ::= 0
  <urban>                ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
  <letter>               ::= A | B | C | E | G | H | J | K | L | M | N |
                             P | R | S | T | V | W | X | Y | Z
  <digit>                ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
